//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKingime.Entity.Mapping
{
    using Core.Data;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 用户数据实体
    /// </summary>
    public partial class User: EntityBase<int>
    {
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public string Username { get; set; }
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public string Password { get; set; }
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public string Nickname { get; set; }
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public Nullable<byte> Gender { get; set; }
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public string Mobile { get; set; }
        
    	/// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> RegisterDate { get; set; }
    }
}
